service: text-to-speech # NOTE: update this with your service name

provider:
  name: aws
  runtime: python2.7
  timeout: 300
  region: eu-west-1
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - polly:*
        - s3:*
      Resource: "*"

functions:
  tospeech:
    handler: api.to_speech
    events:
      - http:
          path: text-to-speech
          method: post
          cors: true
